### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by asasinowski** [asasinowski/TPUM#3]
## Do zrobienia:

- [x] .gitignore
- [x] README.md
- [x] Repository description
- [ ] social preview
- [x] License
- [ ]  Code of conduct
- [ ]  Contributing or use [default one](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file)
- [ ] sponsor button
- [ ] add NuGet packages
- [ ] add common resources and t4 definitions
- [ ] fix compiler errors
- [ ] fix Unit tests
- [ ] README.md
- [ ] Wiki or GitHub pages
- [ ] Repository website
- [ ] Make release
- [ ] Add API Browser in folder `docs/help`
- [ ] Info in the master project if applicable
